name: CI
on: push

jobs:
  test:
    runs-on: kmiles-fedora
    # container:
    #   # image: localhost/py3env
    #   image: katevdi/vdi-conda:latest
    #   options: "-v /w:/w:ro -p 5000:5000"
    steps:
    - uses: actions/checkout@v4 # need to configure auth token
    # - uses: actions/setup-node@v1
    # - run: bash tests/setup-test-container.sh
    # - run: bash tests/run-tests.sh
    - run: uname -a
    - run: pwd
    - run: touch /tmp/hello-ci

# Do actions run pushes to non-main branches?
